package com.codechallenge.bank.util;

import com.codechallenge.bank.exception.DataNotFoundException;
import com.codechallenge.bank.exception.InvalidParameterException;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

/**
 * This class is intended to control the exceptions generated by the application to return the expected error messages.
 *
 * @author Carlos Rodriguez
 * @since 26/09/2019
 */
@ControllerAdvice
public class BankControllerAdvice {

    @ResponseBody
    @ExceptionHandler(DataNotFoundException.class)
    @ResponseStatus(HttpStatus.NOT_FOUND)
    public String dataNotFoundHandler(final DataNotFoundException ex) {
        return ex.getMessage();
    }

    @ResponseBody
    @ExceptionHandler(InvalidParameterException.class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public String invalidParameterHandler(final InvalidParameterException ex) {
        return ex.getMessage();
    }
}